site_name: Autheon
site_description: OAuth2 3rd party integration library for your favorite framework
repo_url: https://github.com/ashgw/autheon
repo_name: ashgw/autheon

theme:
    name: material
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

nav:
    - Home: index.md
    - API Reference: api.md

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details

plugins:
    - search
    - autorefs:
          link_titles: true
    - mkdocstrings:
          handlers:
              python:
                  paths: [.]
                  options:
                      show_source: true
                      show_root_heading: true
                      show_category_heading: true
                      show_bases: true
