blank_issues_enabled: true
contact_links:
    - name: Ask a question
      url: https://github.com/AshGw/autheon/discussions/categories/general
      about: Ask questions and discuss with other community members
