name: docs

on:
    push:
        branches:
            - main
            - xx
    pull_request:
        types:
            - opened
            - synchronize

permissions:
    contents: write

jobs:
    docs:
        if: github.event_name == 'push'
        environment: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
            - uses: actions/cache@v3
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
            - name: UV setup
              run: |
                  bash scripts/ci/uv_setup
            - name: Install documentation dependencies
              run: |
                  uv pip install \
                    'mkdocs>=1.5.3,<2.0.0' \
                    'mkdocs-material>=9.1.21,<10.0.0' \
                    'mkdocstrings[python]>=0.24.0,<0.25.0' \
                    'mkdocs-material-extensions>=1.3.1,<2.0.0'
            - name: Build and deploy documentation
              run: |
                  mkdocs gh-deploy --force
