name: docs

on:
    push:
        branches:
            - main
            - xx
    pull_request:
        types:
            - opened
            - synchronize

permissions:
    contents: write

jobs:
    docs:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install \
                    'mkdocs-material>=9.1.21,<10.0.0' \
                    'mkdocstrings[python]>=0.24.0,<0.25.0' \
                    'mkdocs-material-extensions>=1.3.1,<2.0.0' \
                    'mkdocs>=1.5.3,<2.0.0'

            - name: Deploy docs
              run: mkdocs gh-deploy --force
