name: CI / coverage

on:
    workflow_call:

permissions:
    contents: write

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: UV setup
              run: |
                  bash scripts/ci/uv_setup

            - name: coverage
              run: python scripts/commands.py coverage

            - run: pip install smokeshow

            - run: smokeshow upload htmlcov
              env:
                  SMOKESHOW_GITHUB_STATUS_DESCRIPTION: CLI Coverage {coverage-percentage}
                  SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 80
                  SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head.sha }}
