name: CI / coverage

on:
    workflow_call:

permissions:
    contents: write
    pull-requests: write

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: UV setup
              run: |
                  bash scripts/ci/uv_setup

            - name: coverage
              run: python scripts/commands.py coverage

            - run: pip install smokeshow

            - name: Upload coverage report
              id: smokeshow
              run: smokeshow upload htmlcov
              env:
                  SMOKESHOW_GITHUB_STATUS_DESCRIPTION: CLI Coverage {coverage-percentage}
                  SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 80
                  SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head.sha }}

            - name: Comment coverage report
              run: |
                  gh pr comment ${{ github.event.pull_request.number }} --body "## Coverage Report
                  Coverage: ${{ steps.smokeshow.outputs.coverage-percentage }}%
                  [View detailed coverage report](${{ steps.smokeshow.outputs.report-url }})

                  ### Summary
                  - Total statements: ${{ steps.smokeshow.outputs.total-statements }}
                  - Missing statements: ${{ steps.smokeshow.outputs.missing-statements }}
                  - Excluded statements: ${{ steps.smokeshow.outputs.excluded-statements }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
