name: test

on:
    push:
        branches:
            - main
            - xx
    pull_request:
        branches:
            - main
            - xx
        types:
            - opened
            - synchronize

permissions:
    contents: write

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pre-commit/action@v3.0.0
              with:
                  extra_args: --all-files --verbose
              env:
                  PRE_COMMIT_COLOR: always

    lint:
        runs-on: ubuntu-latest
        needs: format
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.11
            - name: Setup
              run: |
                  bash scripts/ci/uv_setup

            - name: lint
              run: python scripts/commands.py lint

    test:
        runs-on: ubuntu-latest
        needs: lint
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Py setup
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: UV setup
              run: |
                  bash scripts/ci/uv_setup

            - name: test
              run: python scripts/commands.py test

    coverage:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: UV setup
              run: |
                  bash scripts/ci/uv_setup

            - name: coverage
              run: python scripts/commands.py coverage

            - run: pip install smokeshow

            - run: smokeshow upload htmlcov
              env:
                  SMOKESHOW_GITHUB_STATUS_DESCRIPTION: CLI Coverage {coverage-percentage}
                  SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 80
                  SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head.sha }}
